apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sstateful
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: cont-1
        image: saipraveen63/repo:db
        ports:
        - containerPort: 3306
       
